'use strict';

function menuReset() {
    // Clear existing menu selections of color highlighting
    document.getElementById("menu-mlb").classList.remove("colors-mlb");
    document.getElementById("menu-diamondbacks").classList.remove("colors-diamondbacks");
    document.getElementById("menu-braves").classList.remove("colors-braves");
    document.getElementById("menu-orioles").classList.remove("colors-orioles");
    document.getElementById("menu-red-sox").classList.remove("colors-red-sox");
    document.getElementById("menu-cubs").classList.remove("colors-cubs");
    document.getElementById("menu-white-sox").classList.remove("colors-white-sox");
    document.getElementById("menu-reds").classList.remove("colors-reds");
    document.getElementById("menu-guardians").classList.remove("colors-guardians");
    document.getElementById("menu-rockies").classList.remove("colors-rockies");
    document.getElementById("menu-tigers").classList.remove("colors-tigers");
    document.getElementById("menu-astros").classList.remove("colors-astros");
    document.getElementById("menu-royals").classList.remove("colors-royals");
    document.getElementById("menu-angels").classList.remove("colors-angels");
    document.getElementById("menu-dodgers").classList.remove("colors-dodgers");
    document.getElementById("menu-marlins").classList.remove("colors-marlins");
    document.getElementById("menu-brewers").classList.remove("colors-brewers");
    document.getElementById("menu-twins").classList.remove("colors-twins");
    document.getElementById("menu-mets").classList.remove("colors-mets");
    document.getElementById("menu-yankees").classList.remove("colors-yankees");
    document.getElementById("menu-athletics").classList.remove("colors-athletics");
    document.getElementById("menu-phillies").classList.remove("colors-phillies");
    document.getElementById("menu-pirates").classList.remove("colors-pirates");
    document.getElementById("menu-padres").classList.remove("colors-padres");
    document.getElementById("menu-giants").classList.remove("colors-giants");
    document.getElementById("menu-mariners").classList.remove("colors-mariners");
    document.getElementById("menu-cardinals").classList.remove("colors-cardinals");
    document.getElementById("menu-rays").classList.remove("colors-rays");
    document.getElementById("menu-rangers").classList.remove("colors-rangers");
    document.getElementById("menu-blue-jays").classList.remove("colors-blue-jays");
    document.getElementById("menu-nationals").classList.remove("colors-nationals");

    document.getElementById("page-body").classList.remove("colors-mlb");
    document.getElementById("page-body").classList.remove("colors-diamondbacks");
    document.getElementById("page-body").classList.remove("colors-braves");
    document.getElementById("page-body").classList.remove("colors-orioles");
    document.getElementById("page-body").classList.remove("colors-red-sox");
    document.getElementById("page-body").classList.remove("colors-cubs");
    document.getElementById("page-body").classList.remove("colors-white-sox");
    document.getElementById("page-body").classList.remove("colors-reds");
    document.getElementById("page-body").classList.remove("colors-guardians");
    document.getElementById("page-body").classList.remove("colors-rockies");
    document.getElementById("page-body").classList.remove("colors-tigers");
    document.getElementById("page-body").classList.remove("colors-astros");
    document.getElementById("page-body").classList.remove("colors-royals");
    document.getElementById("page-body").classList.remove("colors-angels");
    document.getElementById("page-body").classList.remove("colors-dodgers");
    document.getElementById("page-body").classList.remove("colors-marlins");
    document.getElementById("page-body").classList.remove("colors-brewers");
    document.getElementById("page-body").classList.remove("colors-twins");
    document.getElementById("page-body").classList.remove("colors-mets");
    document.getElementById("page-body").classList.remove("colors-yankees");
    document.getElementById("page-body").classList.remove("colors-athletics");
    document.getElementById("page-body").classList.remove("colors-phillies");
    document.getElementById("page-body").classList.remove("colors-pirates");
    document.getElementById("page-body").classList.remove("colors-padres");
    document.getElementById("page-body").classList.remove("colors-giants");
    document.getElementById("page-body").classList.remove("colors-mariners");
    document.getElementById("page-body").classList.remove("colors-cardinals");
    document.getElementById("page-body").classList.remove("colors-rays");
    document.getElementById("page-body").classList.remove("colors-rangers");
    document.getElementById("page-body").classList.remove("colors-blue-jays");
    document.getElementById("page-body").classList.remove("colors-nationals");

}